info <- rbebelm_backend_info()
expect_true(inherits(info, "rbebelmBackendInfo"))
expect_true(is.list(info))
expect_true("selected_backend" %in% names(info))
expect_true(grepl("Rbebelm backend dispatch", paste(capture.output(print(info)), collapse = "\n")))

cpu <- rbebelm_cpuid_info()
expect_true(inherits(cpu, "rbebelmCpuidInfo"))
expect_true(is.list(cpu))
expect_true("cpu_dotprod" %in% names(cpu))
expect_true(grepl("Rbebelm CPU features", paste(capture.output(print(cpu)), collapse = "\n")))

features <- rbebelm_backend_features()
expect_true(inherits(features, "rbebelmBackendFeatures"))
expect_true(is.list(features))
expect_true("model_storage" %in% names(features))
expect_true(grepl("Rbebelm backend features", paste(capture.output(print(features)), collapse = "\n")))
