api <- readLines("src/rust/api.h", warn = FALSE)
proto <- grep("^SEXP savvy_.*__ffi\\(", api, value = TRUE)
if (!length(proto)) stop("no savvy FFI prototypes found in src/rust/api.h")

parse_proto <- function(x) {
  m <- regexec("^SEXP (savvy_.*__ffi)\\((.*)\\);$", x)
  r <- regmatches(x, m)[[1]]
  if (length(r) != 3L) stop("cannot parse prototype: ", x)
  sym <- r[[2]]
  args <- trimws(r[[3]])
  base <- sub("^savvy_", "", sub("__ffi$", "", sym))
  dispatch_base <- sub("^rbebelm_", "", base)
  dispatch <- paste0("Rbebelm_", dispatch_base, "_ffi")
  args_decl <- if (identical(args, "void")) "void" else args
  arg_names <- character()
  if (!identical(args, "void")) {
    parts <- trimws(strsplit(args, ",", fixed = TRUE)[[1]])
    arg_names <- sub("^SEXP[[:space:]]+", "", parts)
  }
  list(sym = sym, dispatch = dispatch, args_decl = args_decl, arg_names = arg_names)
}

ffis <- lapply(proto, parse_proto)

# Patch src/init.c generated by savvy so .Call wrappers call the runtime dispatcher.
path <- "src/init.c"
x <- readLines(path, warn = FALSE)
x <- gsub('#include "rust/api.h"', '#include "rbebelm_backend.h"', x, fixed = TRUE)
for (f in ffis) {
  x <- gsub(f$sym, f$dispatch, x, fixed = TRUE)
}
needle <- '    {NULL, NULL, 0}'
extra <- c(
  '    {"Rbebelm_set_backend_impl", (DL_FUNC) &Rbebelm_set_backend_impl, 1},',
  '    {"Rbebelm_backend_info_impl", (DL_FUNC) &Rbebelm_backend_info_impl, 0},',
  '    {"Rbebelm_cpuid_info_impl", (DL_FUNC) &Rbebelm_cpuid_info_impl, 0},'
)
i <- which(x == needle)
if (length(i) != 1L) stop("could not find CallEntries terminator in src/init.c")
if (!any(grepl("Rbebelm_set_backend_impl", x, fixed = TRUE))) {
  x <- append(x, extra, after = i - 1L)
}
writeLines(x, path)

# Generate dispatcher prototypes in src/rbebelm_backend.h.
h <- readLines("src/rbebelm_backend.h", warn = FALSE)
start <- grep("^SEXP Rbebelm_.*_ffi\\(", h)[1]
end <- grep("^#endif", h)[1] - 1L
if (is.na(start) || is.na(end) || start > end) stop("cannot find generated FFI declaration block in rbebelm_backend.h")
decls <- vapply(ffis, function(f) sprintf("SEXP %s(%s);", f$dispatch, f$args_decl), character(1))
h <- c(h[seq_len(start - 1L)], decls, "", h[(end + 1L):length(h)])
writeLines(h, "src/rbebelm_backend.h")

# Generate dispatcher typedefs, symbol loads, and forwarding wrappers in src/rbebelm_backend.c.
c <- readLines("src/rbebelm_backend.c", warn = FALSE)

start <- grep("^typedef SEXP \\(\\*fn_", c)[1]
end <- grep("^static int backend_loaded", c)[1] - 1L
if (is.na(start) || is.na(end) || start > end) stop("cannot find function pointer block in rbebelm_backend.c")
typedefs <- unlist(Map(function(f, i) {
  args <- if (identical(f$args_decl, "void")) "void" else paste(rep("SEXP", length(f$arg_names)), collapse = ", ")
  c(
    sprintf("typedef SEXP (*fn_%03d)(%s);", i, args),
    sprintf("static fn_%03d p_%03d = NULL;", i, i)
  )
}, ffis, seq_along(ffis)), use.names = FALSE)
c <- c(c[seq_len(start - 1L)], typedefs, "", c[(end + 1L):length(c)])

load_lines <- grep("^[[:space:]]*p_.*load_symbol\\(handle, \"savvy_", c)
if (!length(load_lines)) stop("cannot find backend symbol load block")
load_start <- load_lines[1]
load_end <- tail(load_lines, 1)
loads <- vapply(seq_along(ffis), function(i) {
  f <- ffis[[i]]
  sprintf("    p_%03d = (fn_%03d)load_symbol(handle, \"%s\");", i, i, f$sym)
}, character(1))
c <- c(c[seq_len(load_start - 1L)], loads, c[(load_end + 1L):length(c)])

wrap_lines <- grep("^SEXP Rbebelm_.*_ffi\\(", c)
if (!length(wrap_lines)) stop("cannot find forwarding wrapper block")
wrap_start <- wrap_lines[1]
wrap_end <- tail(wrap_lines, 1)
wrappers <- vapply(seq_along(ffis), function(i) {
  f <- ffis[[i]]
  call <- if (length(f$arg_names)) paste(f$arg_names, collapse = ", ") else ""
  sprintf("SEXP %s(%s) { Rbebelm_init_backend(); return p_%03d(%s); }", f$dispatch, f$args_decl, i, call)
}, character(1))
c <- c(c[seq_len(wrap_start - 1L)], wrappers, "", c[(wrap_end + 1L):length(c)])
writeLines(c, "src/rbebelm_backend.c")
