# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib Rbebelm, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_Rbebelm__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_Rbebelm__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' Return BebeLM stream event types.
#' @export
`bebel_event_types` <- function() {
  .Call(savvy_bebel_event_types__impl)
}

#' Return BebeLM tokenizer special token ids.
#' @export
`bebel_token_ids` <- function() {
  .Call(savvy_bebel_token_ids__impl)
}

#' Return feature information reported by the loaded Rust backend.
#' @export
`rbebelm_backend_features` <- function() {
  .Call(savvy_rbebelm_backend_features__impl)
}

#' Parse upstream BebeLM Pythonic tool calls.
#' @keywords internal
`rbebelm_parse_tool_calls` <- function(`text`) {
  .Call(savvy_rbebelm_parse_tool_calls__impl, `text`)
}

#' Render an upstream BebeLM ChatML system turn, optionally with tool schemas.
#' @keywords internal
`rbebelm_render_system_turn` <- function(`message`, `tool_names`, `tool_schemas`) {
  .Call(savvy_rbebelm_render_system_turn__impl, `message`, `tool_names`, `tool_schemas`)
}

### wrapper functions for BebelAgent

`BebelAgent_append` <- function(self) {
  function(`text`) {
    .Call(savvy_BebelAgent_append__impl, `self`, `text`)
  }
}

`BebelAgent_append_system` <- function(self) {
  function(`message`) {
    .Call(savvy_BebelAgent_append_system__impl, `self`, `message`)
  }
}

`BebelAgent_append_system_with_tools` <- function(self) {
  function(`message`, `tool_names`, `tool_schemas`) {
    .Call(savvy_BebelAgent_append_system_with_tools__impl, `self`, `message`, `tool_names`, `tool_schemas`)
  }
}

`BebelAgent_append_tokens` <- function(self) {
  function(`ids`) {
    .Call(savvy_BebelAgent_append_tokens__impl, `self`, `ids`)
  }
}

`BebelAgent_append_tool_result` <- function(self) {
  function(`content`) {
    .Call(savvy_BebelAgent_append_tool_result__impl, `self`, `content`)
  }
}

`BebelAgent_append_user` <- function(self) {
  function(`message`) {
    .Call(savvy_BebelAgent_append_user__impl, `self`, `message`)
  }
}

`BebelAgent_assistant_turn` <- function(self) {
  function(`check_interrupt`, `on_event` = NULL) {
    .Call(savvy_BebelAgent_assistant_turn__impl, `self`, `check_interrupt`, `on_event`)
  }
}

`BebelAgent_assistant_turn_async` <- function(self) {
  function() {
    .savvy_wrap_BebelAsyncJob(.Call(savvy_BebelAgent_assistant_turn_async__impl, `self`))
  }
}

`BebelAgent_assistant_turn_tool_stop` <- function(self) {
  function(`check_interrupt`, `on_event` = NULL) {
    .Call(savvy_BebelAgent_assistant_turn_tool_stop__impl, `self`, `check_interrupt`, `on_event`)
  }
}

`BebelAgent_assistant_turn_tool_stop_async` <- function(self) {
  function() {
    .savvy_wrap_BebelAsyncJob(.Call(savvy_BebelAgent_assistant_turn_tool_stop_async__impl, `self`))
  }
}

`BebelAgent_clear` <- function(self) {
  function() {
    .Call(savvy_BebelAgent_clear__impl, `self`)
  }
}

`BebelAgent_clone` <- function(self) {
  function() {
    .savvy_wrap_BebelAgent(.Call(savvy_BebelAgent_clone__impl, `self`))
  }
}

`BebelAgent_configure` <- function(self) {
  function(`greedy` = NULL, `max_gen` = NULL, `max_context` = NULL, `max_think` = NULL, `temperature` = NULL, `top_k` = NULL, `repeat_penalty` = NULL) {
    .Call(savvy_BebelAgent_configure__impl, `self`, `greedy`, `max_gen`, `max_context`, `max_think`, `temperature`, `top_k`, `repeat_penalty`)
  }
}

`BebelAgent_generate` <- function(self) {
  function(`check_interrupt`, `on_event` = NULL) {
    .Call(savvy_BebelAgent_generate__impl, `self`, `check_interrupt`, `on_event`)
  }
}

`BebelAgent_generate_async` <- function(self) {
  function() {
    .savvy_wrap_BebelAsyncJob(.Call(savvy_BebelAgent_generate_async__impl, `self`))
  }
}

`BebelAgent_history` <- function(self) {
  function() {
    .Call(savvy_BebelAgent_history__impl, `self`)
  }
}

`BebelAgent_info` <- function(self) {
  function() {
    .Call(savvy_BebelAgent_info__impl, `self`)
  }
}

`BebelAgent_prefill` <- function(self) {
  function(`check_interrupt`) {
    .Call(savvy_BebelAgent_prefill__impl, `self`, `check_interrupt`)
  }
}

`BebelAgent_transcript` <- function(self) {
  function() {
    .Call(savvy_BebelAgent_transcript__impl, `self`)
  }
}

`.savvy_wrap_BebelAgent` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`append` <- `BebelAgent_append`(ptr)
  e$`append_system` <- `BebelAgent_append_system`(ptr)
  e$`append_system_with_tools` <- `BebelAgent_append_system_with_tools`(ptr)
  e$`append_tokens` <- `BebelAgent_append_tokens`(ptr)
  e$`append_tool_result` <- `BebelAgent_append_tool_result`(ptr)
  e$`append_user` <- `BebelAgent_append_user`(ptr)
  e$`assistant_turn` <- `BebelAgent_assistant_turn`(ptr)
  e$`assistant_turn_async` <- `BebelAgent_assistant_turn_async`(ptr)
  e$`assistant_turn_tool_stop` <- `BebelAgent_assistant_turn_tool_stop`(ptr)
  e$`assistant_turn_tool_stop_async` <- `BebelAgent_assistant_turn_tool_stop_async`(ptr)
  e$`clear` <- `BebelAgent_clear`(ptr)
  e$`clone` <- `BebelAgent_clone`(ptr)
  e$`configure` <- `BebelAgent_configure`(ptr)
  e$`generate` <- `BebelAgent_generate`(ptr)
  e$`generate_async` <- `BebelAgent_generate_async`(ptr)
  e$`history` <- `BebelAgent_history`(ptr)
  e$`info` <- `BebelAgent_info`(ptr)
  e$`prefill` <- `BebelAgent_prefill`(ptr)
  e$`transcript` <- `BebelAgent_transcript`(ptr)

  class(e) <- c("Rbebelm::BebelAgent", "BebelAgent", "savvy_Rbebelm__sealed")
  e
}


#' Persistent BebeLM conversation agent with transcript and decode caches.
#' @export
`BebelAgent` <- new.env(parent = emptyenv())

### associated functions for BebelAgent

`BebelAgent`$`new` <- function(`model`, `greedy`, `max_gen` = NULL, `max_context` = NULL, `max_think` = NULL, `temperature` = NULL, `top_k` = NULL, `repeat_penalty` = NULL) {
  `model` <- .savvy_extract_ptr(`model`, "Rbebelm::BebelModel")
  .savvy_wrap_BebelAgent(.Call(savvy_BebelAgent_new__impl, `model`, `greedy`, `max_gen`, `max_context`, `max_think`, `temperature`, `top_k`, `repeat_penalty`))
}


class(`BebelAgent`) <- c("Rbebelm::BebelAgent__bundle", "savvy_Rbebelm__sealed")

#' @export
`print.Rbebelm::BebelAgent__bundle` <- function(x, ...) {
  cat('Rbebelm::BebelAgent\n')
}

### wrapper functions for BebelAsyncJob

`BebelAsyncJob_events` <- function(self) {
  function(`max` = NULL) {
    .Call(savvy_BebelAsyncJob_events__impl, `self`, `max`)
  }
}

`BebelAsyncJob_ready` <- function(self) {
  function() {
    .Call(savvy_BebelAsyncJob_ready__impl, `self`)
  }
}

`BebelAsyncJob_result` <- function(self) {
  function(`wait`) {
    .Call(savvy_BebelAsyncJob_result__impl, `self`, `wait`)
  }
}

`.savvy_wrap_BebelAsyncJob` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`events` <- `BebelAsyncJob_events`(ptr)
  e$`ready` <- `BebelAsyncJob_ready`(ptr)
  e$`result` <- `BebelAsyncJob_result`(ptr)

  class(e) <- c("Rbebelm::BebelAsyncJob", "BebelAsyncJob", "savvy_Rbebelm__sealed")
  e
}


#' Background BebeLM generation job.
#' @export
`BebelAsyncJob` <- new.env(parent = emptyenv())

### associated functions for BebelAsyncJob



class(`BebelAsyncJob`) <- c("Rbebelm::BebelAsyncJob__bundle", "savvy_Rbebelm__sealed")

#' @export
`print.Rbebelm::BebelAsyncJob__bundle` <- function(x, ...) {
  cat('Rbebelm::BebelAsyncJob\n')
}

### wrapper functions for BebelModel

`BebelModel_chat` <- function(self) {
  function(`message`, `greedy`, `check_interrupt`, `on_event` = NULL, `max_gen` = NULL, `max_context` = NULL, `max_think` = NULL, `temperature` = NULL, `top_k` = NULL, `repeat_penalty` = NULL) {
    .Call(savvy_BebelModel_chat__impl, `self`, `message`, `greedy`, `check_interrupt`, `on_event`, `max_gen`, `max_context`, `max_think`, `temperature`, `top_k`, `repeat_penalty`)
  }
}

`BebelModel_chat_async` <- function(self) {
  function(`message`, `greedy`, `max_gen` = NULL, `max_context` = NULL, `max_think` = NULL, `temperature` = NULL, `top_k` = NULL, `repeat_penalty` = NULL) {
    .savvy_wrap_BebelAsyncJob(.Call(savvy_BebelModel_chat_async__impl, `self`, `message`, `greedy`, `max_gen`, `max_context`, `max_think`, `temperature`, `top_k`, `repeat_penalty`))
  }
}

`BebelModel_decode` <- function(self) {
  function(`ids`) {
    .Call(savvy_BebelModel_decode__impl, `self`, `ids`)
  }
}

`BebelModel_embed` <- function(self) {
  function(`text`, `add_bos`, `normalize`, `pooling`) {
    .Call(savvy_BebelModel_embed__impl, `self`, `text`, `add_bos`, `normalize`, `pooling`)
  }
}

`BebelModel_embed_batch` <- function(self) {
  function(`text`, `add_bos`, `normalize`, `pooling`, `check_interrupt`, `token_batch_size` = NULL) {
    .Call(savvy_BebelModel_embed_batch__impl, `self`, `text`, `add_bos`, `normalize`, `pooling`, `check_interrupt`, `token_batch_size`)
  }
}

`BebelModel_encode` <- function(self) {
  function(`text`, `add_bos`) {
    .Call(savvy_BebelModel_encode__impl, `self`, `text`, `add_bos`)
  }
}

`BebelModel_generate` <- function(self) {
  function(`prompt`, `greedy`, `check_interrupt`, `on_event` = NULL, `max_gen` = NULL, `max_context` = NULL, `max_think` = NULL, `temperature` = NULL, `top_k` = NULL, `repeat_penalty` = NULL) {
    .Call(savvy_BebelModel_generate__impl, `self`, `prompt`, `greedy`, `check_interrupt`, `on_event`, `max_gen`, `max_context`, `max_think`, `temperature`, `top_k`, `repeat_penalty`)
  }
}

`BebelModel_generate_async` <- function(self) {
  function(`prompt`, `greedy`, `max_gen` = NULL, `max_context` = NULL, `max_think` = NULL, `temperature` = NULL, `top_k` = NULL, `repeat_penalty` = NULL) {
    .savvy_wrap_BebelAsyncJob(.Call(savvy_BebelModel_generate_async__impl, `self`, `prompt`, `greedy`, `max_gen`, `max_context`, `max_think`, `temperature`, `top_k`, `repeat_penalty`))
  }
}

`BebelModel_info` <- function(self) {
  function() {
    .Call(savvy_BebelModel_info__impl, `self`)
  }
}

`.savvy_wrap_BebelModel` <- function(ptr) {
  e <- new.env(parent = emptyenv())
  e$.ptr <- ptr
  e$`chat` <- `BebelModel_chat`(ptr)
  e$`chat_async` <- `BebelModel_chat_async`(ptr)
  e$`decode` <- `BebelModel_decode`(ptr)
  e$`embed` <- `BebelModel_embed`(ptr)
  e$`embed_batch` <- `BebelModel_embed_batch`(ptr)
  e$`encode` <- `BebelModel_encode`(ptr)
  e$`generate` <- `BebelModel_generate`(ptr)
  e$`generate_async` <- `BebelModel_generate_async`(ptr)
  e$`info` <- `BebelModel_info`(ptr)

  class(e) <- c("Rbebelm::BebelModel", "BebelModel", "savvy_Rbebelm__sealed")
  e
}


#' Loaded BebeLM GGUF model.
#' @export
`BebelModel` <- new.env(parent = emptyenv())

### associated functions for BebelModel

`BebelModel`$`load` <- function(`path`, `num_threads` = NULL) {
  .savvy_wrap_BebelModel(.Call(savvy_BebelModel_load__impl, `path`, `num_threads`))
}


class(`BebelModel`) <- c("Rbebelm::BebelModel__bundle", "savvy_Rbebelm__sealed")

#' @export
`print.Rbebelm::BebelModel__bundle` <- function(x, ...) {
  cat('Rbebelm::BebelModel\n')
}

